name: Get My Browser
on: [push, workflow_dispatch]

jobs:
  download-and-zip:
    runs-on: windows-latest
    steps:
      - name: Grab Files
        run: |
          mkdir out
          cd out
          curl -L -o app.exe https://twibright.com
          7z x app.exe
          del app.exe
          echo @echo off > Run.bat
          echo links2.exe -g -base-dir "%%CD%%\userdata" >> Run.bat

      - name: Send Zip
        uses: actions/upload-artifact@v4
        with:
          name: Links-Portable
          path: out/
